"""Add title and description columns to Reminder

Revision ID: e976f27863ab
Revises: f1dc25ffbd74
Create Date: 2025-01-12 13:16:44.483667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e976f27863ab'
down_revision = 'f1dc25ffbd74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
